version: '3'

networks:
  local:

services:
  php72:
    container_name: app_php72
    image: sonypiay/php-apache:7.2
    tty: true
    ports:
      - '81:80'
    networks:
      - local
    restart: always
  
  php73:
    container_name: app_php73
    image: sonypiay/php-apache:7.3
    tty: true
    ports:
      - '82:80'
    networks:
      - local
    restart: always

  php74:
    container_name: app_php74
    image: sonypiay/php-apache:7.4
    tty: true
    ports:
      - '83:80'
    networks:
      - local
    restart: always